### ISSUE TITLE
Allow logged-in users to submit new tables

### ISSUE THREAD

**Issue by hylandtechoutreach** [hylandtechoutreach/uct-locator#2]

**Comment by josephmaxwellhyland** [comment]
Work on a front-end page where users can fill out information for a table and submit it to the back-end

**Comment by josephmaxwellhyland** [comment]
Back-end of this is covered by #39 but still need the front-end part

**Comment by josephmaxwellhyland** [comment]
When submitting tables, the `coordinateLocation` field is required. It may be necessary to convert an address to coordinates; this is possible using the [Geocoding Service](https://developers.google.com/maps/documentation/javascript/geocoding) from Google Maps.

**Comment by josephmaxwellhyland** [comment]
Page setup in the **components/Tables/SubmitTable.js** file. Will want to create the form, try to make it look similar to login and register pages and use [MUI](https://mui.com/) components. You will want to make a POST request using `axios` - this will be kind of similar to the Login and Register
