### ISSUE TITLE
Update the Table schema to include the proper fields

### ISSUE THREAD

**Issue by josephmaxwellhyland** [hylandtechoutreach/uct-locator#21]
Refer to this document for a rundown of the different fields: https://docs.google.com/document/d/1hvNCYMRI2hwdve5Q7m8n8atQRLNjMW6ztJRf5RfIGmE/edit#

**Comment by brebory** [comment]
Again I'll plug Web Dev Simplified: https://www.youtube.com/watch?v=DZBGEVgL2eE
