### ISSUE TITLE
Find a Table: Add a header and paragraph explaining the basics of the page

### ISSUE THREAD

**Issue by josephmaxwellhyland** [hylandtechoutreach/uct-locator#96]
Currently, the "Find a Table" page has a functional map, but not much introductory information.

In the **front-end/src/components/Map/LocationViewMap.js** file, in the inner `<div>`, above the `<Wrapper>`, there should be a header and a paragraph. The header should say "Find a Table" and the paragraph should say "Use this map to find the location of a universal changing table!"

**Comment by matandon** [comment]
#99
